# Generated by Django 6.0.1 on 2026-01-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonustransfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='bonustransfer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Удален администратором'),
        ),
        migrations.AddField(
            model_name='bonustransfer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='transfer_documents/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='bonustransfer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Объяснение причины'),
        ),
        migrations.AddField(
            model_name='bonustransfer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='bonustransfer',
            name='reason',
            field=models.CharField(blank=True, choices=[('excellent_work', 'Отличная работа'), ('help_colleague', 'Помощь коллеге'), ('project_success', 'Успешный проект'), ('innovation', 'Инновация'), ('teamwork', 'Командная работа'), ('client_satisfaction', 'Довольный клиент'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Причина перевода'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('transfer_received', 'Получен перевод'), ('transfer_cancelled', 'Перевод отменен'), ('news', 'Новость'), ('system', 'Системное')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.bonustransfer', verbose_name='Связанный перевод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
