# Generated by Django 6.0.1 on 2026-01-23 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_bonustransfer_deleted_at_bonustransfer_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_bonus_amount', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Сумма бонусных рублей на месяц')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип компании')),
            ],
            options={
                'verbose_name': 'Настройка системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='participates_in_bonus',
            field=models.BooleanField(default=True, verbose_name='Участвует в системе премирования'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='employee_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль в системе'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='participates_in_bonus',
            field=models.BooleanField(default=True, verbose_name='Участвует в системе премирования'),
        ),
    ]
